from collections.abc import Collection, Mapping
from pathlib import Path
from typing import Self

class url:
    class Query:
        def __init__(self, querystr: str) -> None: ...
        def add(self, key: str, value: str) -> None: ...
        def get(self) -> Mapping[str, Collection[str]]: ...
        def encode(self) -> str: ...
        def add_map(self, map: Mapping[str, str]) -> None: ...
        def set_map(self, map: Mapping[str, str]) -> None: ...
        def remove(self, key: str) -> None: ...
        def copy(self) -> Self: ...
        def omit_empty_equal(self) -> str: ...
        def sort(self) -> None: ...
        def first(self) -> Mapping[str, str]: ...
        def compare(self, other: Self) -> bool: ...
        @property
        def params(self) -> Mapping[str, Collection[str]]: ...

    class Path:
        def __init__(self, pathstr: str) -> None: ...
        def add(self, pathstr: str) -> None: ...
        def add_path(self, pathobj: Path) -> None: ...
        def clear(self) -> None: ...
        def is_dir(self) -> bool: ...
        def encode(self) -> str: ...
        def normalize(self) -> None: ...
        def copy(self) -> Self: ...
        def get(self) -> Collection[str]: ...
        def compare(self, other: Self) -> bool: ...
        @property
        def segments(self) -> Collection[str]: ...

    class Fragment:
        def __init__(self, fragmentstr: str) -> None: ...
        def encode(self) -> str: ...
        def set(self, fragmentstr: str) -> None: ...
        def copy(self) -> Self: ...
        def compare(self, other: Self) -> bool: ...

    class Netloc:
        username: str | None
        password: str | None
        host: str
        port: int | None
        def __init__(self, netloc: str) -> None: ...
        def encode(self) -> str: ...
        def parse(self, netloc: str) -> None: ...
        def set(
            self,
            host: str | None = None,
            port: int | None = None,
            username: str | None = None,
            password: str | None = None,
        ) -> None: ...
        def merge(self, other: Self) -> Self: ...
        def merge_left(self, other: Self) -> Self: ...
        def merge_inplace(self, other: Self) -> None: ...
        @staticmethod
        def from_args(
            host: str,
            port: int | None = None,
            username: str | None = None,
            password: str | None = None,
        ) -> url.Netloc: ...
        def copy(self) -> Self: ...
        def compare(self, other: Self) -> bool: ...

    class URL:
        scheme: str
        netloc: url.Netloc
        path: url.Path
        query: url.Query
        fragment: url.Fragment

        def __init__(self, url: str) -> None: ...
        def encode(self, append_empty_equal: bool = True) -> str: ...
        def add(
            self,
            path: str | None = None,
            query: Mapping[str, str] | None = None,
            fragment: str | None = None,
            netloc: str | None = None,
            netloc_obj: url.Netloc | None = None,
            scheme: str | None = None,
        ) -> None: ...
        def set(
            self,
            path: str | None = None,
            query: Mapping[str, str] | None = None,
            fragment: str | None = None,
            netloc: str | None = None,
            netloc_obj: url.Netloc | None = None,
            scheme: str | None = None,
        ) -> None: ...
        @staticmethod
        def from_netloc(
            netloc: url.Netloc | None = None,
            username: str | None = None,
            password: str | None = None,
            host: str | None = None,
            port: int | None = None,
        ) -> url.URL: ...
        @staticmethod
        def from_args(
            path: str | None = None,
            query: Mapping[str, str] | None = None,
            fragment: str | None = None,
            netloc: str | None = None,
            netloc_obj: url.Netloc | None = None,
            scheme: str | None = None,
        ) -> url.URL: ...
        def copy(self) -> Self: ...
        def compare(self, other: Self) -> bool: ...

class strings:
    @staticmethod
    def replace_all(value: str, replacements: Mapping[str, str]) -> str: ...
    @staticmethod
    def replace_by(
        value: str, replacement: str, to_replace: Collection[str]
    ) -> str: ...
    @staticmethod
    def to_snake(value: str) -> str: ...
    @staticmethod
    def to_camel(value: str) -> str: ...
    @staticmethod
    def to_pascal(value: str) -> str: ...
    @staticmethod
    def to_kebab(
        value: str, remove_trailing_underscores: bool = True
    ) -> str: ...
    @staticmethod
    def squote(value: str) -> str: ...
    @staticmethod
    def dquote(value: str) -> str: ...
    @staticmethod
    def sentence(value: str) -> str: ...
    @staticmethod
    def exclamation(value: str) -> str: ...
    @staticmethod
    def question(value: str) -> str: ...
